[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "scientific-computing-handbook"
authors = [{name = "Philip Mocz", email = "philip.mocz@gmail.com"}]
dynamic = ["version", "description"]
